default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: locbinh
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: auto_rails_development

test:
  <<: *default
  database: auto_rails_test

production:
  <<: *default
  database: auto_rails_production
  username: root
  password: binhbong93

